"""Preguntas propuestas manualmente a partir de secciones localizadas del corpus GLF.

Formato: pregunta, documento abreviado, número de fragmento, ancla textual exacta.
El ancla se valida en el texto original antes de exportar la referencia.
"""
DOCS = {
    'M':'GLF_MANUAL_SGAS_ES',
    'A':'GLF_ANEXO_A_POLITICA_AMBIENTAL_SOCIAL_ES',
    'B':'GLF_ANEXO_B_LISTA_EXCLUSION_ES',
    'C':'GLF_ANEXO_C_NORMAS_AMBIENTALES_SOCIALES_ES',
    'D':'GLF_ANEXO_D_MARCO_JURIDICO_PERMISOS_ES',
    'E':'GLF_ANEXO_E_HERRAMIENTA_ESSA_ES',
    'F':'GLF_ANEXO_F_CLAUSULAS_CONVENIOS_SUBVENCION_ES',
    'G1':'GLF_ANEXO_G1_PLANTILLA_PLAN_PARTICIPACION_PARTES_INTERESADAS_ES',
    'G2':'GLF_ANEXO_G2_PLANTILLA_MECANISMO_RECLAMACIONES_ES',
    'G':'GLF_ANEXO_G_PLANTILLA_PGAS_ES',
    'H':'GLF_ANEXO_H_FUNCIONES_RESPONSABILIDADES_SGAS_ES',
    'I':'GLF_ANEXO_I_HERRAMIENTA_SEGUIMIENTO_AMBIENTAL_SOCIAL_ES',
    'J':'GLF_ANEXO_J_DEFINICIONES_ES',
}

SPECS = [
    ('¿Cuál es el área de influencia territorial y marina descrita por el SGAS del GLF?', 'M',2,'1.2.1 Área de influencia'),
    ('¿Cuál es el objetivo y propósito del Sistema de Gestión Ambiental y Social del GLF?', 'M',2,'2.1 Objetivo y propósito'),
    ('¿Qué responsabilidades corresponden a las entidades subvencionadas en el SGAS?', 'M',3,'2.2.2 Entidades subvencionadas'),
    ('¿Qué documentos y pasos integran la detección ambiental y social de una propuesta?', 'M',4,'6.1.2 Paso 2: detección ambiental y social'),
    ('¿Cómo clasifica el GLF los proyectos por nivel de riesgo ambiental y social?', 'M',4,'Categorización de riesgo'),
    ('¿Qué debe revisar el GLF durante la evaluación de la detección ambiental y social?', 'M',5,'6.1.3 Paso 3: evaluación de la detección'),
    ('¿Qué ocurre en la fase de ejecución y monitoreo del PGAS?', 'M',5,'6.1.7 Paso 7: ejecución y monitoreo'),
    ('¿Cómo se aplica el principio de precaución y la norma más rigurosa en la política del GLF?', 'A',2,'2 Principio de precaución y cumplimiento de la norma más rigurosa'),
    ('¿Qué establece la política del GLF sobre la jerarquía de mitigación?', 'A',2,'3 Principio de jerarquía'),
    ('¿Qué establece la política frente a la violencia sexual y de género?', 'A',3,'6 Principio de tolerancia cero frente a la violencia sexual y de género'),
    ('¿Cómo aborda la política los derechos y condiciones laborales?', 'A',3,'7 Principio de derechos de los trabajadores y condiciones laborales'),
    ('¿Se excluyen actividades con alto riesgo de introducir especies invasoras en áreas protegidas de Galápagos?', 'B',1,'3. Actividades que impliquen riesgos considerables de introducción de especies invasoras'),
    ('¿Excluye el GLF actividades de desplazamiento forzoso o reasentamiento involuntario?', 'B',1,'7. Actividades que impliquen desplazamiento forzoso'),
    ('¿Qué operaciones extractivas excluye la lista del GLF?', 'B',1,'12. Actividades que comprendan la prospección'),
    ('¿Qué indica la lista de exclusión sobre proyectos de Categoría A de riesgo alto?', 'B',2,'14. Proyectos clasificados por el GLF como Categoría A'),
    ('¿Se incluye la construcción de represas en la lista de exclusión del GLF?', 'B',2,'15. Construcción de represas'),
    ('¿Qué estándares internacionales y buenas prácticas enumera el Anexo C?', 'C',1,'## Normas ambientales y sociales'),
    ('¿Qué marco jurídico de planificación y gestión se aplica en Galápagos?', 'D',4,'2.2 Marco jurídico de planificación y gestión'),
    ('¿Cómo se regulan las áreas protegidas conforme al Código Orgánico del Ambiente?', 'D',5,'2.3.1 Regulación de áreas protegidas conforme al COA'),
    ('¿Qué normas trata el marco jurídico para residuos y desechos?', 'D',6,'2.3.2 Gestión de residuos, desechos y otros productos'),
    ('¿Qué contempla el marco jurídico sobre pueblos indígenas y consentimiento previo?', 'D',8,'La Constitución garantiza a comunas'),
    ('¿Qué autorización ambiental corresponde a proyectos de impacto bajo?', 'D',10,'Impacto bajo: registro ambiental'),
    ('¿Cómo se usa la hoja de lista de exclusión en la herramienta ESSA?', 'E',1,'Hoja 2. Lista de Exclusión'),
    ('¿Qué preguntas ambientales y sociales se hacen sobre trabajo y condiciones laborales en la nota conceptual?', 'E',2,'B. Trabajo y condiciones laborales'),
    ('¿Qué temas de biodiversidad se revisan en la detección ambiental y social?', 'E',3,'F. Biodiversidad y recursos naturales vivos'),
    ('¿Qué instrumentos de salvaguarda puede pedir la herramienta ESSA?', 'E',4,'## Requisitos específicos posibles'),
    ('¿Qué obligaciones sobre SGAS y PGAS se incorporan en convenios de subvención?', 'F',1,'2.1 Responsabilidad de cumplir los requisitos del SGAS e implementar el PGAS'),
    ('¿Cómo se notifican accidentes e incidentes graves en los convenios de subvención?', 'F',2,'Anexo 4 Instrumentos de notificación de accidentes e incidentes graves'),
    ('¿Qué debe incluir la introducción del Plan de Participación de las Partes Interesadas?', 'G1',1,'## Introducción'),
    ('¿Cómo se identifican y mapean las partes interesadas de un proyecto?', 'G1',2,'Identificación y mapeo de las partes interesadas'),
    ('¿Qué información debe contener el cronograma de participación planificada?', 'G1',3,'Cronograma de actividades'),
    ('¿Cuáles son los principios operativos del mecanismo de reclamaciones?', 'G2',1,'Principios operativos'),
    ('¿Cuáles son las etapas del proceso de reclamaciones para proyectos financiados por el GLF?', 'G2',2,'Proceso para proyectos financiados por el GLF'),
    ('¿Cómo se evalúa la admisibilidad de una reclamación?', 'G2',3,'Evaluación de admisibilidad'),
    ('¿Qué información debe registrar el formulario de reclamaciones?', 'G2',4,'Anexo 1-B Formulario del Mecanismo de Reclamaciones'),
    ('¿Qué información básica del proyecto incluye la plantilla del PGAS?', 'G',2,'Información del Proyecto'),
    ('¿Cómo se resume en el PGAS la estrategia para gestionar riesgos e impactos?', 'G',3,'Estrategia de gestión de riesgos'),
    ('¿Cómo se organizan funciones y responsabilidades para implementar el PGAS?', 'G',4,'### Funciones y responsabilidades'),
    ('¿Qué indica la plantilla del PGAS sobre seguimiento, evaluación e informes?', 'G',4,'Seguimiento evaluación e informes'),
    ('¿Qué instrumentos esenciales de salvaguarda se integran en el PGAS?', 'G',5,'Instrumentos esenciales de salvaguarda'),
    ('¿Qué indica el PGAS sobre preparación para emergencias?', 'G',6,'### Respuesta ante emergencias'),
    ('¿Qué funciones tiene la Junta Directiva dentro del SGAS del GLF?', 'H',1,'## Junta Directiva'),
    ('¿Qué responsabilidades tienen los responsables de programas en el SGAS?', 'H',2,'Responsables de Programas'),
    ('¿Cómo se registra el seguimiento del PGAS en la herramienta ambiental y social?', 'I',2,'1 Pestañas de seguimiento del PGAS'),
    ('¿Qué información está reservada para el GLF en el informe ESMO?', 'I',3,'2 Informe ESMO'),
    ('¿Cómo define el corpus del GLF el consentimiento libre, previo e informado?', 'J',2,'Consentimiento libre previo e informado'),
    ('¿Qué es un plan de gestión de residuos según las definiciones del SGAS?', 'J',5,'Plan de gestión de residuos'),
    ('¿Qué prácticas pesqueras destructivas excluye el GLF?', 'B',1,'9. Actividades que impliquen prácticas pesqueras destructivas'),
    ('¿Qué indica la exclusión sobre organizaciones sospechosas de corrupción?', 'B',2,'16. Empresas u organizaciones respecto de las cuales'),
    ('¿Cómo se organiza el programa de participación de las partes interesadas?', 'G1',2,'Programa de participación de las partes interesadas'),
]
